name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.0.3  # Adjusted version
  - pytest=7.4.2  # Adjusted version
  - scipy=1.11.3
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
